2021-04-03 10:40:42,525 ERROR: Exception on /program/Mass Gen [GET] [in a:\projects\match\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "a:\projects\match\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "a:\projects\match\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "A:\projects\match\app\main\routes.py", line 90, in program
    return render_template('program.html', program=program, form=form)
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "a:\projects\match\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "A:\projects\match\app\templates\program.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "A:\projects\match\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "A:\projects\match\app\templates\base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "A:\projects\match\app\templates\program.html", line 11, in block "app_content"
    {% if not current_user.is_following_program(program) %}
  File "A:\projects\match\app\models.py", line 134, in is_following_program
    console.log(self.programs)
NameError: name 'console' is not defined
2021-04-03 10:41:47,775 ERROR: Exception on /program/Mass Gen [GET] [in a:\projects\match\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "a:\projects\match\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "a:\projects\match\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "A:\projects\match\app\main\routes.py", line 90, in program
    return render_template('program.html', program=program, form=form)
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "a:\projects\match\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "A:\projects\match\app\templates\program.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "A:\projects\match\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "A:\projects\match\app\templates\base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "A:\projects\match\app\templates\program.html", line 11, in block "app_content"
    {% if not current_user.is_following_program(program) %}
  File "A:\projects\match\app\models.py", line 134, in is_following_program
    return 1
NameError: name 'console' is not defined
2021-04-04 04:14:35,152 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
